### ISSUE TITLE
Freezes when launching application on Quest.

### ISSUE THREAD

**Issue by quezdk** [handzlikchris/Unity.QuestRemoteHandTracking#5]
The application freezes after the loading screen.

**Comment by hetnieuwekader** [comment]
Experiencing the same. Application works fine with RemoteHandTracking is disabled.
Unity version: 2019.2.1f1

**Comment by handzlikchris** [comment]
Cheers guys I'll double check tomorrow on clean setup and will get back to you

**Comment by handzlikchris** [comment]
I tried to recreate that with no luck, even when I dropped off WiFi with Quest or specified invalid IP address. 

The only thing I've noticed is it gets bit slow with invalid network setup. Probably due to exceptions being thrown when it tries to send messages.

1) Bit daft question but when you say that scene runs it means that you can actually use your hands there in train scene (without remote-tracking component turned on)?
Just want to double check that your quest is on beta channel (with hand tracking) as without it it'd error when using new APIs.

2) Unlikely but maybe quest version causes issues. What version are you on? Is it same as the one I'm testing?
Version: 12.0.0.226.469.188362039
Runtime Version: 12.0.0.226.469.188362025

3) Other than than is there anything in logcat?

Generally if it can't connect you'll see some errors like
`01-15 09:57:33.507: I/Unity(5016): On client connect exception System.Net.Sockets.SocketException (0x80004005): No route to host`

`01-15 09:57:27.508: E/Unity(5016): Keep alive error, System.InvalidOperationException: The operation is not allowed on non-connected sockets.`

If the setup is fine you'll see some data being sent
`01-15 09:59:38.406: I/Unity(5191): UDP Connected hands data endpoint`
`01-15 09:59:44.151: I/Unity(5191): Message sent (size: 2948)`

**Comment by handzlikchris** [comment]
@MikkelVirsabi @hetnieuwekader any news guys?

**Comment by handzlikchris** [comment]
I'll close this one as it's been a while, I hope you've managed to solve it.
